//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Customer = new HashSet<Customer>();
            this.Staff = new HashSet<Staff>();
        }
    
        public short AddressId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public short CityId { get; set; }
        public string PoBOX { get; set; }
        public string Phone { get; set; }
        public byte[] LastUpdate { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
