//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ItemCategory = new HashSet<ItemCategory>();
        }
    
        public byte CategoryId { get; set; }
        public string Name { get; set; }
        public byte[] LastUpdate { get; set; }
    
        public virtual ICollection<ItemCategory> ItemCategory { get; set; }
    }
}
