//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Address = new HashSet<Address>();
        }
    
        public short CityId { get; set; }
        public string Name { get; set; }
        public byte[] LastUpdate { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
    }
}
