//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Rental = new HashSet<Rental>();
            this.Payment = new HashSet<Payment>();
        }
    
        public short CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public short AddressId { get; set; }
        public bool Active { get; set; }
        public byte[] LastUpdate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Rental> Rental { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
