//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Rentals = new HashSet<Rental>();
            this.ItemCategory = new HashSet<ItemCategory>();
        }
    
        public int ItemId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PurchuseDate { get; set; }
        public byte RentalDuration { get; set; }
        public decimal RentalPrice { get; set; }
        public decimal Price { get; set; }
        internal byte[] LastUpdate { get; set; }
    
        public virtual ICollection<Rental> Rentals { get; set; }
        public virtual ICollection<ItemCategory> ItemCategory { get; set; }
    }
}
