//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public Rental()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int RentalId { get; set; }
        public System.DateTime RentalDate { get; set; }
        public int ItemId { get; set; }
        public short CutomerId { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public byte StaffId { get; set; }
        public byte[] LastUpdate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Item Item { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
