//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Rental = new HashSet<Rental>();
            this.Payment = new HashSet<Payment>();
        }
    
        public byte StaffId { get; set; }
        public byte JobRoleId { get; set; }
        public Nullable<byte> ManagerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public short AddressID { get; set; }
        public byte[] Picture { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public string Username { get; set; }
        public byte[] LastUpdate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual JobRole JobRole { get; set; }
        public virtual ICollection<Rental> Rental { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Staff Staff2 { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
